### ISSUE TITLE
Add roadmap, either roadmap.md or issues

### ISSUE THREAD

**Issue by marcosvega91** [smeijer/testing-playground#1]
Hi @smeijer 

thanks for this project :). I want to contribute in some way. Can you create a list of issues with what you think to implement or where you want an hand?
I see that you haven't tested the application, maybe it could be a starting point.

 Thanks :)

Regards
Marcp

**Comment by smeijer** [comment]
Hi! 

Creating a couple of issues that can serve as kind of a roadmap, sounds like a good plan. Thanks :)

The things I had in mind to work on post-release are (in no particular order):

- interactive HTML (Will deployed **SOON**, see #2)
- update readme with dev instructions
- create some instructions for how to use the playground
  - Do we need this?
  - If we do, it should be shown on testing-playground.com as well.
- add some tests (using jest & testing-library)
- figure out how emoji-key works, so contributors will be acknowledged in the readme.

And a couple of more things. But I'll create some issues for those.

Also important; would be to get some user feedback. Blindly adding functionality can be awesome. But knowing what the users are missing is worth a lot.

**Comment by smeijer** [comment]
I've added a bunch of issues and documented them in [ROADMAP.md](https://github.com/smeijer/testing-playground/blob/master/ROADMAP.md) for easier reading.

All idea's are open for contributions.
