### ISSUE TITLE
Webmanifest icon links are invalid

### ISSUE THREAD

**Issue by ljosberinn** [smeijer/testing-playground#142]
Looks like during build, Parcel prefixes the urls in there with `../public/<img>` (which isnt even valid in the first place as they are placed on the top level) but also does not attach the correct hashes.

![image](https://user-images.githubusercontent.com/29307652/84520538-03803700-acd4-11ea-83e2-66880999cb61.png)
![image](https://user-images.githubusercontent.com/29307652/84520560-09761800-acd4-11ea-83d9-5b87bdf3e20a.png)

**Comment by ljosberinn** [comment]
Interestingly, it works on deploy previews:
![image](https://user-images.githubusercontent.com/29307652/84523681-0598c480-acd9-11ea-910c-d4cca1c02ae6.png)

**Comment by smeijer** [comment]
Has already been fixed. Let me update production :)

**Comment by smeijer** [comment]
Should be fixed now.

**Comment by smeijer** [comment]
> Interestingly, it works on deploy previews:

Yeah, I've disabled the option to deploy every PR to production at the moment, because we have moments that we are merging quite a lot.

Might enable it again pretty soon. But for this moment, I think it's better to deploy after a couple of PR's.
