### ISSUE TITLE
Sandbox code evaluation / prevent redirections

### ISSUE THREAD

**Issue by marcosvega91** [smeijer/testing-playground#21]
Trying to test the parser I see that in the editor you can write everything. There is not check on what you are writing. You can write for example `alert('hello')` or whatever.

I think that we need to parse the string before evaluate it, extracting method and check it is enabled to use.

**Comment by smeijer** [comment]
Why would that be a problem? Are there security concerns that we need to think about?

The alert example is something I can also do on `codepen` or `jsfiddle`

**Comment by marcosvega91** [comment]
Security I think that now is not a problem. I don't know If is correct to enable the user to write what  he wants. I thought that it was a bug.

**Comment by smeijer** [comment]
I understand your concern, but unless I'm missing something serious, I think that's exactly what we want.

The most serious javascript injection that I'm aware of is about:

 - session hijacking
 - cookie stealing
 - code injection

**Session Hijacking**
We don't have any sessions, or server side, so I'm not worried about this

**Cookie stealing**
We don't have cookies

**Code injection**
Code injection usually means that you write a comment or something, and by executing javascript you change the functionality behind some buttons or redirect your user to another site.

It is now possible to add a redirect, and forward the user to your own site when you would share the playground URL. I can imagine that we should block things like that.

For example, add something like this to your playground:

```js
window.location.href = 'https://google.com';
```
[playground](https://testing-playground.com/#DwIwrgLhD2B2BQsCGBbApgXgEQGcCWA5rGAA5bwQCeJmuYIKeE5AfPkacAPThRwtA&O4SwdgJg9sB0A2UDGBDALiKZYAsBOApgGYAEAvCQEQ5poAOAXAPRMDmUUr8BsSUAtpSA)

**Comment by smeijer** [comment]
Thinking about this, I think this can be done quite easily.

If we would evaluate the query inside an iframe (maybe just in the preview pane?), the only thing that would be redirected, would be the iframe.

**Comment by marcosvega91** [comment]
Now there is no problem. The only strange thing about it is that the `eval` function will evaluate everything but the result is only for the last sentence. So it could be strange

**Comment by smeijer** [comment]
True, but we would make it quite difficult for ourselves if we would only execute the last expression.

```js
const role = 'button';
screen.getByRole(role);
```

**Comment by marcosvega91** [comment]
You are right

**Comment by smeijer** [comment]
Got the sandboxing thing working. I'll submit a PR in a couple of days.
