### ISSUE TITLE
playground is showing query suggestions when there are none

### ISSUE THREAD

**Issue by smeijer** [smeijer/testing-playground#30]
I'm not sure what's nice about this one:

![image](https://user-images.githubusercontent.com/1196524/82993415-ce4fc580-a000-11ea-876f-6a1616fb0cea.png)

[playground](https://testing-playground.com/#DwGwhgRgpiAEBmB7ATgXgEQFcDOVkDswBbKdAPgFVcDipgB6caEMoA&MYewdgLghglmCmAnIA)

And I'm not sure what's great about this one either:

![image](https://user-images.githubusercontent.com/1196524/82993450-dad41e00-a000-11ea-89a6-f33f264ff90a.png)

[playground](https://testing-playground.com/#Q&MYewdgLghglmCmAnIA)

**Comment by delca85** [comment]
hey @smeijer I suppose I have found the source of the bugs (at least of one of them).
How do you prefer the playground appears in case of:
1. no element is entered by the user in the first box?
2. no query is entered by the user?

I mean that I would like to know if a box (and what kind of box) appears instead of the _suggested query_ one?
Thanks!

**Comment by marcosvega91** [comment]
I think that in both cases we can suggest to the user what he can do with the playground like an 'how to'.

**Comment by smeijer** [comment]
A suggestion on what he should do, accompanied by a nice illustration from https://undraw.co/illustrations?

**Comment by delca85** [comment]
If it's ok for all of you, I am on it.
Any suggestion about how the short "How to" should appear would be appreciated!

**Comment by smeijer** [comment]
That would be awesome, I've been playing a bit in dev-tools, how about something like this for "example 2":

![image](https://user-images.githubusercontent.com/1196524/83329729-6bbe2a00-a28b-11ea-9b67-b339564c0e2c.png)

The image used is "Code thinking" from undraw.co, with the color set to `#EDF2F7` and opacity of `.5`

**Comment by delca85** [comment]
@smeijer great!!
Maybe, I could add a brief explanation after `I don't know what to say`? Just one or two sentences where I could tell that this is a playground for React Testing Library.
Or would you prefer just the sentence you suggested?

**Comment by smeijer** [comment]
Sounds good to me. :+1:
