### ISSUE TITLE
import `testing-library/dom` from npm instead of unpkg

### ISSUE THREAD

**Issue by smeijer** [smeijer/testing-playground#65]
This comment needs to be fixed:

quoting for issue indexing:

> This is not the way I want it to be, but I can't get '@testing-library/dom'
> to build with Parcel. Something with "Incompatible receiver, Map required".
> It works when running parcel in dev mode, but not in build mode. Seems to
> have something to do with a core-js Map polyfill being used?
> It's now loaded from unpkg.com via ./index.html

https://github.com/smeijer/testing-playground/blob/958a46b4be8520045908ac1d20de8236e45409f5/src/parser.js#L5-L16

**Comment by smeijer** [comment]
Actually, I think I've changed my mind.

Fetching it from unpkg gives us an advantage. It will allow us to add an option to switch the version of testing-library that's being used.

@marcosvega91 & @MichaelDeBoey, what do you guys think?

**Comment by marcosvega91** [comment]
I like the idea, can be interesting

**Comment by MichaelDeBoey** [comment]
Being able to switch the version could be helpful to test possible bugs with, but I'm not sure if we should make this available tbh.
I think we should help strive towards pushing the newest version.

**Comment by Siemko** [comment]
I hope this helps a bit, in my opinion testing-playground should always aim for the newest version of testing-library. I think it aims to be the guiding light, and we want it to point to the best possible right direction. @MichaelDeBoey here is right.

**Comment by smeijer** [comment]
Some help in fixing the issue would be most welcome 😇

**Comment by Siemko** [comment]
I'll have a look after my working hours :eyes:

**Comment by smeijer** [comment]
> I'll have a look after my working hours :eyes: 

Thanks. That would be awesome!

**Comment by Siemko** [comment]
This one's nasty. Generally speaking, `parcel` uses `core-js@3` from `@babel/runtime-corejs3` to provide all the polyfills. Of course map polyfill is not a Map, and there is some checking done. I was trying to play with babel configuration, I can change some settings, but it seems like `@babel/runtime-corejs3` is always applied by parcel.

What I know by now:
1. Parcel's not taking `.babelrc` into consideration during build unless `"env"` option is specified
2. Providing 
```
"presets": [
    ["@babel/preset-env", { "corejs": false }],
    "@babel/preset-react"
  ],
"plugins": [["@babel/plugin-transform-runtime", { "corejs": false }]],
```
to both `.babelrc` root and `env.production` has no influence on how parcel transforms it.

I'm confused, will keep on working this out tomorrow.

**Comment by smeijer** [comment]
Yeah, what I remember form another project of mine, is that parcel does do something "smart" with browserslists.

I think we need to write a browserslist file to the testing-library folder before build.

Also see here: https://github.com/parcel-bundler/parcel/issues/1655#issuecomment-561139492

If that doesn't work, we have a few options left.

- open an issue at parcel-bunder
- fix the issue in testing lib
- add testing lib as git sub module

The last one is really least preferable in my opinion.

**Comment by smeijer** [comment]
The issue lies within `aria-query`, but so far I've been unable to get it to work. I've filed an issue in the parcel repo: https://github.com/parcel-bundler/parcel/issues/4692
