### ISSUE TITLE
question: why the parse function returns also an id?

### ISSUE THREAD

**Issue by marcosvega91** [smeijer/testing-playground#66]
I'm looking at the code, in particular to the parse function.

```js
let id = 0;

function parse({ htmlRoot, js }) {
  let result = {
    // increment the id every time we call parse, so we can use
    // it for react keys, when iterating over targets
    id: ++id,
  };
```

Is the id important to the parse function? I looked at the code but I didn't found the place where it is used.

**Comment by smeijer** [comment]
No, I removed it while working on the sandboxing thing (#21). During the prototyping phase, I used it to force rerenders some elements.

Will submit a PR for it soon.
