### ISSUE TITLE
Crashes on mousemove

### ISSUE THREAD

**Issue by ljosberinn** [smeijer/testing-playground#87]
In this [REPL](https://testing-playground.com/?markup=AQHgRg9gJgnsDGAbAhgZ1QXgESIJYHMALAFwFoBbaAUywD4AoEKXAN3qTUywBUI1iqAJyz1cUbIKrJ4ZYn1TERDEKgAOyAHbsU6bL35CA%2BofKbk%2BIaTmqRCmIirZTAD1IB3McUIAuYAFYANgAGVWcAbmBVCFRcYlwIDV8AM1xnKigIgC9SXA0oKmdfPz8goIio3IFBUioWKg1iVF8NBKoI00F8XN8Q52BkAFc5CIFnMmQ8fESEeqqRiFUe0IjBAhIl8OAHJOINsJEAemU1TW1OPXkq41MNc0trUm3FejsHJ2RXDygvIuDlyOisXi0xSaQywGyuXyhX8JTKAMqllqsyawBaGjawGsey2VB2e0Ox3UWg4uh4lyMJjMFmqD1WRGer0cWBc7k8Pn8f02URicQSyVS6SyOTyBSKcPKEER1WRDVR6Mx2OAvRWa12yuWhMYJxJOi4%2BgUlJud2qkGIcnIjzxjOI9mZrK%2BP05KoBvOBArBwqhYthpUl0pqdTlzVaETNFpxTwJ9CO2uJZzJBquVNuNNI4Yg5FstreLI%2BbO%2BHMCLp5QP5wFBQohIuh4r9CIaSKDjRDGPayE63Q1fUGwyxBXGk2m8FmQjDEHNmb29Hp627ESj861KnjpP1FME12plgzltnNrt70%2B7N%2BJcBfJBgvBkNFMOK9YqjZlzfloeAu5x%2B%2BjsZAB2YLGUf9ANYBA9WweB0FIII6EYMAhjkLQO1wZBSHgBJiEECBEC4ch6gGUgAEZoPoJCUIKYl8nELAMIGGgSNWFDCDQKJVAGVQnDwkQ13AyCCLAToNACAAOEQxA4jQBjgycNEIgiREw3MpIQkRbVUZklISJRtRYfAEy4CDUEI1QACsCKEgBmFgRBSRBEHAgZBEkBoAGEsIgYR6EIKg1WwAiqCzF4MIgABrZl4AcpziFcxB3OzTDQoLLxsGIlhcCoNwACEIGcZLlWAAAmAAWArCpER1CF8-yRGcchEA0LgSGIRYDgONw2oAOjccz2vc-ADny0oggOVAdK0kB1C8egqIAWQI-L2qEgB2YACL8dqgkWxBSHmvxCu29q-AI9bzNIY74COxa9qOgBOYr5uuoTSEK9qCMW%2BhusWgjSACA7zIACVegA1QrCFIRbAfyv6hJYSGCJYG7rsIAijte5zkYO4BFva678pWoJ2sK4rrvaxa-GAa6VqO8yyaE9blqI9rzNxrHzPJl6KZ%2BgIKaE0H8vgEnWaOgJBYF4ButegrsaE4BnsCLa1qCCmFfygAZYqCOuxA-FIMnxYIsWXougJ9qCQrMlm2myaI3mVbmgr8sIfLEBR-LSHMwhntJlX8v1-KHadp6DsI-LMkteaAmZ532ojwPzPM23ibt17Qe6orMmXYadIYFXNHwAY7lQRgDg0jRgLYUjHmQMAqFs9IwBgcTJPghJZK4sCsAMwjjLcKhVHgAJRKo3CJMI4iFPtTjAsPLBSwvXwq9QLChjaFSq%2B9HKsEI6rSFUFAR2H4hsF3Mb-z0njDLHrDmXwTC2LG1RQPODveLAABHJJyDcCAYIAQRYZBcAoDAA4LYud84WELr%2BVQygS70WQqhLy8BQpURonRCuzBUBVwcFRNuT9O7kEyFEIIzwMFYPSNgeSV9G6xH8oIZAzBv70GIGvW82At70H-ogWi2B6hjRGrpCuhAxD5A0NgVBuCySd3wKoDQhB4AwBEFAZAzCKB4RoZaXAaFRFYGshAcKmDgHMiSBMVAdFx7YFUJIUxDRlHAhEKldKWUN5BDygRdWpV6DKHwBWQBdkO4RVmNFWKygoiIBgPgBIDZGjYDWlbBG1046mxWsVbqhVroJPMkEcyFM5oY1xrE%2BgtN0kZKyTkjGz10nCQCH4XGLifppJKdkrAwAfwHHwMoTO7S4yaEfpI3i%2BdqnpzLr0-SkFMiFR0oQZwMEQC4HIAIxAh8sAAHEMoiEEcI%2BoYjBC0VsIIeA2BGqqCaC1AYGhVDBXwO1NC5ADiSGkGQJIKB8CkGCrEAAAvjcWBxOBUEaAcVZ7V%2BHZmnl5NUvgir-HKhCwq-wMG72QDAXwuQ8AYnTDFJB%2BwYwdKAvQAAohofAeBUCECLjqDpJcYHN0QgxBBVAkHkKwMY7CdFuLP0MgQohzxzEsjUQIcgdCGGrzAOvZK9iJjcKwPkPhOk4GMU2do8RZ92WESlFAMAExFHKJQsPAY6ichaIofQJIeiBgGNzMy0xlDcyWKoNY5hF57FpUytlXKLi3HJLGt4myfjwqOUCW5YQISsLhMiY%2BaJWBYmU2xukxJ7iDYNMSdklaO0Cr%2BAOoUmNjSylkwqddKpNS8r1NjZkppLSOldN-PwokPS2WdwIgMvwQzGD-hGefUg4zJnTOUHMhZSyAAieL1m0qEVAER2zdkvH2Yc80xzvCnPOZc65mY7lSBkKQJ55hXkfK%2BS9H56A-moAOIOoFo0p65jBQyGFUKTwlThbgNQKAkXABRbkKg6K9HBSxa03FyyhA3DJcSCl1KcWsGUIQQQcrSDuTSjYi8hyYOZHQpq5V9aUjwCCAMaZ2LGDIFQ5BYKAwoCZBQxBvEM6monLabEQgkll23MQMZaI1dVgaA0AcNSghF63C2vc9dkBAFCARQIA48ka7YBaJIJIQhJCCDRBABY9QhDWonhJdRwrRWbzkkwjsFglmGGAZoYKWk-o1wfhhTQqAUBxEJfQbSuk628UWlAVQ5kYDPBNfosh2BLVmKoTPKxsxbGaQ4c6pxbqSolS9ca3xEnWhxRCmFAJLlA0JYSqi%2BlyB2JMoGLZNL77yrYHyvfZRhBgAzTMitSyARkC41qa47aBU-p%2BFq2mlx7rtrbUBkJVrtT6DuoKttQgA9y2MAmmViruthssBGz%2Bcb5XsCzXdYVb2%2BtzLNNaZWzpHTkCgYAkXXFv5DvF2gDAWgQA&query=PTAEEUFcFMCcE9TwPaVqaAbaBbaA7AFwGdQALOaAGlAAdZoAzOAQwCNNEB3AS0LIBQIUAANiAYwYEAdAHNohAELxAZAQAKFQEoR00AElGSVKHEt8AckKhIxaELASp%2Ba7dHjkRFj3xxpARxgEAGUsaHFCZFgNbWkBexMPQi8fWH9A%2BBDscMi1c29aSEJzTQFHaBl5JXgAJWRsXLx8SD5cWBYAEx5kcxoAbwF8FjwALlBzAFF8WUweYjJzAQBfTSA)

![image](https://user-images.githubusercontent.com/29307652/83698692-60a82880-a602-11ea-9282-7ecd9dd3669c.png)

![image](https://user-images.githubusercontent.com/29307652/83698706-669e0980-a602-11ea-823d-aefb6c807231.png)

Thanks for this tool!

**Comment by smeijer** [comment]
Thanks for the repl link, that's very helpful!

This bug has been fixed. I did find some other issue while playing with your reply, that one I've filed under #91.
