### ISSUE TITLE
make it embeddable

### ISSUE THREAD

**Issue by smeijer** [smeijer/testing-playground#9]
How awesome would it be if we had an embed-mode, so users can embed the playground in the blogs they write about testing / testing-library?

---
Resources:
- https://twitter.com/edouardr_/status/1264474482116354048?s=19

**Comment by MichaelDeBoey** [comment]
Let me know whenever this is possible, so I can add it as a built-in transformer for [`gatsby-rark-embedder`](https://github.com/MichaelDeBoey/gatsby-remark-embedder) 👊

**Comment by smeijer** [comment]
@MichaelDeBoey, do you have idea's about how it should look? What kind of functionality you would want in embed mode?

**Comment by MichaelDeBoey** [comment]
@smeijer If you look at @codesandbox or @CodePen, you see it's always a miniature version of the real app.

They're both providing an [oembed](https://oembed.com/) endpoint, which returns an object with an `html` key that has the embeddable `iframe`.

**Comment by smeijer** [comment]
Thanks, I have something to read tomorrow :+1:  Never heard of oembed before.

**Comment by smeijer** [comment]
@MichaelDeBoey , embed mode is almost done. But I'm not sure how soon I will have oembed implemented. As that requires a server side (beyond static hosting), I need to figure a few things out.

Maybe it's possible via netlify functions, but I've never worked with those before.

Preview can be seen here: https://codepen.io/smeijer/pen/yLYWZmK

**Comment by smeijer** [comment]
Been working a bit more on it, I don't think that oembed will be that hard after all :)

**Comment by MichaelDeBoey** [comment]
@smeijer It really looks nice!
This would be something entirely inside of an `iframe` I think?

**Comment by smeijer** [comment]
@MichaelDeBoey , embeddable is done!

We support `oembed` as well as "custom" embed:

The custom embedding can be seen here: 

https://codepen.io/smeijer/pen/yLYWZmK?editors=1000

The `oembed` isn't really visible yet, as I don't know of any `oembed` validators that can render the thing without requiring a submission first, but it [passes](https://embed.ly/providers/validate/oembed?endpoint=https%3A%2F%2Ftesting-playground.com%2Foembed&url=https%3A%2F%2Ftesting-playground.com) the `embed.ly` validator:



![image](https://user-images.githubusercontent.com/1196524/83151399-cf661d00-a0fc-11ea-9a37-1cbe9abe3e19.png)

**Comment by smeijer** [comment]
To answer your question, yes, it renders the thing in an `iframe`. It would be possible to render it in a `div` instead though. Would that be preferable?

**Comment by MichaelDeBoey** [comment]
@smeijer Providing an `iframe` is perfect for me! 👊

I'll check it out later today and I'll let you know if I need some extra info or I think something isn't working like it should be 😉

**Comment by smeijer** [comment]
Please let me know when you have something working as well :innocent: , can't wait to see it in action.

**Comment by MichaelDeBoey** [comment]
I've created MichaelDeBoey/gatsby-remark-embedder#123 with the reason to drop it soon 😉

**Comment by MichaelDeBoey** [comment]
@smeijer If you wanna take a go on it yourself btw, it can be yours 😉

**Comment by smeijer** [comment]
Do you know how to get [iframely](https://iframely.com/embed) to render the embedded thing?

I know that for [`embed.ly`](http://embed.ly/) we must submit an application. But I can't find anything for iframely.


> @smeijer If you wanna take a go on it yourself btw, it can be yours

I can take a look. But don't wait for me if you can do it faster.

**Comment by MichaelDeBoey** [comment]
> Do you know how to get [iframely](https://iframely.com/embed) to render the embedded thing?

I haven't worked with iframely yet, so would have to look it up myself.

> I can take a look. But don't wait for me if you can do it faster.

I can probably do it faster, but I like to help people getting into the plugin.
So if you want, be my guest 😉

**Comment by smeijer** [comment]
Not really, I have plenty of other things to do. So if you can do that, it would be much appreciated.

I've just completed the application at embed.ly. Let's see how that goes.

**Comment by MichaelDeBoey** [comment]
Gonna eat and I'll create a PR for Testing Playground support 🙂

**Comment by smeijer** [comment]
Support Request is running for iframely.

![image](https://user-images.githubusercontent.com/1196524/83180530-dbb1a080-a123-11ea-82d6-ad81c296fc5b.png)

**Comment by smeijer** [comment]
[we're whitelisted on iframely!](https://iframely.com/embed/https%3A%2F%2Ftesting-playground.com%2F%3Fmarkup%3DDwIwrgLhD2B2B8AoANtA5gS1o4B6cUc8QA%26query%3DM4YwTgphB2B0DmEAuAhAngJQPYBsIAoByAIwFckktpCBKIA%26panes%3Dmarkup%2Cquery)

![image](https://user-images.githubusercontent.com/1196524/83190483-c4c67a80-a132-11ea-911b-e8277cb38fed.png)

**Comment by MichaelDeBoey** [comment]
Wooohooo!! 🎉🎉🎉
