### ISSUE TITLE
invalid suggestion on hover

### ISSUE THREAD

**Issue by smeijer** [smeijer/testing-playground#91]
When hovering the flag images in this [repl][repl], the preview area suggests a `getByRole` query.

Yet, when we apply that query by clicking the flag, the suggestion pane renders an error:

![image](https://user-images.githubusercontent.com/1196524/83735948-46496b80-a651-11ea-8882-287d7fd0221b.png)

[repl]: https://testing-playground.com/?markup=AQHgRg9gJgnsDGAbAhgZ1QXgESIJYHMALAFwFoBbaAUywD4AoEKXAN3qTUywBUI1iqAJyz1cUbIKrJ4ZYn1TERDEKgAOyAHbsU6bL35CA%2BofKbk%2BIaTmqRCmIirZTAD1IB3McUIAuYAFYANgAGVWcAbmBVCFRcYlwIDV8AM1xnKigIgC9SXA0oKmdfPz8goIio3IFBUioWKg1iVF8NBKoI00F8XN8Q52BkAFc5CIFnMmQ8fESEeqqRiFUe0IjBAhIl8OAHJOINsJEAemU1TW1OPXkq41MNc0trUm3FejsHJ2RXDygvIuDlyOisXi0xSaQywGyuXyhX8JTKAMqllqsyawBaGjawGsey2VB2e0Ox3UWg4uh4lyMJjMFmqD1WRGer0cWBc7k8Pn8f02URicQSyVS6SyOTyBSKcPKEER1WRDVR6Mx2OAvRWa12yuWhMYJxJOi4%2BgUlJud2qkGIcnIjzxjOI9mZrK%2BP05KoBvOBArBwqhYthpUl0pqdTlzVaETNFpxTwJ9CO2uJZzJBquVNuNNI4Yg5FstreLI%2BbO%2BHMCLp5QP5wFBQohIuh4r9CIaSKDjRDGPayE63Q1fUGwyxBXGk2m8FmQjDEHNmb29Hp627ESj861KnjpP1FME12plgzltnNrt70%2B7N%2BJcBfJBgvBkNFMOK9YqjZlzfloeAu5x%2B%2BjsZAB2YLGUf9ANYBA9WweB0FIII6EYMAhjkLQO1wZBSHgBJiEECBEC4ch6gGUgAEZoPoJCUIKYl8nELAMIGGgSNWFDCDQKJVAGVQnDwkQ13AyCCLAToNACAAOEQxA4jQBjgycNEIgiREw3MpIQkRbVUZklISJRtRYfAEy4CDUEI1QACsCKEgBmFgRBSRBEHAgZBEkBoAGEsIgYR6EIKg1WwAiqCzF4MIgABrZl4AcpziFcxB3OzTDQoLLxsGIlhcCoNwACEIGcZLlWAAAmAAWArCpER1CF8-yRGcchEA0LgSGIRYDgONw2oAOjccz2vc-ADny0oggOVAdK0kB1C8egqIAWQI-L2qEgB2YACL8dqgkWxBSHmvxCu29q-AI9bzNIY74COxa9qOgBOYr5uuoTSEK9qCMW%2BhusWgjSACA7zIACVegA1QrCFIRbAfyv6hJYSGCJYG7rsIAijte5zkYO4BFva678pWoJ2sK4rrvaxa-GAa6VqO8yyaE9blqI9rzNxrHzPJl6KZ%2BgIKaE0H8vgEnWaOgJBYF4ButegrsaE4BnsCLa1qCCmFfygAZYqCOuxA-FIMnxYIsWXougJ9qCQrMlm2myaI3mVbmgr8sIfLEBR-LSHMwhntJlX8v1-KHadp6DsI-LMkteaAmZ532ojwPzPM23ibt17Qe6orMmXYadIYFXNHwAY7lQRgDg0jRgLYUjHmQMAqFs9IwBgcTJPghJZK4sCsAMwjjLcKhVHgAJRKo3CJMI4iFPtTjAsPLBSwvXwq9QLChjaFSq%2B9HKsEI6rSFUFAR2H4hsF3Mb-z0njDLHrDmXwTC2LG1RQPODveLAABHJJyDcCAYIAQRYZBcAoDAA4LYud84WELr%2BVQygS70WQqhLy8BQpURonRCuzBUBVwcFRNuT9O7kEyFEIIzwMFYPSNgeSV9G6xH8oIZAzBv70GIGvW82At70H-ogWi2B6hjRGrpCuhAxD5A0NgVBuCySd3wKoDQhB4AwBEFAZAzCKB4RoZaXAaFRFYGshAcKmDgHMiSBMVAdFx7YFUJIUxDRlHAhEKldKWUN5BDygRdWpV6DKHwBWQBdkO4RVmNFWKygoiIBgPgBIDZGjYDWlbBG1046mxWsVbqhVroJPMkEcyFM5oY1xrE%2BgtN0kZKyTkjGz10nCQCH4XGLifppJKdkrAwAfwHHwMoTO7S4yaEfpI3i%2BdqnpzLr0-SkFMiFR0oQZwMEQC4HIAIxAh8sAAHEMoiEEcI%2BoYjBC0VsIIeA2BGqqCaC1AYGhVDBXwO1NC5ADiSGkGQJIKB8CkGCrEAAAvjcWBxOBUEaAcVZ7V%2BHZmnl5NUvgir-HKhCwq-wMG72QDAXwuQ8AYnTDFJB%2BwYwdKAvQAAohofAeBUCECLjqDpJcYHN0QgxBBVAkHkKwMY7CdFuLP0MgQohzxzEsjUQIcgdCGGrzAOvZK9iJjcKwPkPhOk4GMU2do8RZ92WESlFAMAExFHKJQsPAY6ichaIofQJIeiBgGNzMy0xlDcyWKoNY5hF57FpUytlXKLi3HJLGt4myfjwqOUCW5YQISsLhMiY%2BaJWBYmU2xukxJ7iDYNMSdklaO0Cr%2BAOoUmNjSylkwqddKpNS8r1NjZkppLSOldN-PwokPS2WdwIgMvwQzGD-hGefUg4zJnTOUHMhZSyAAieL1m0qEVAER2zdkvH2Yc80xzvCnPOZc65mY7lSBkKQJ55hXkfK%2BS9H56A-moAOIOoFo0p65jBQyGFUKTwlThbgNQKAkXABRbkKg6K9HBSxa03FyyhA3DJcSCl1KcWsGUIQQQcrSDuTSjYi8hyYOZHQpq5V9aUjwCCAMaZ2LGDIFQ5BYKAwoCZBQxBvEM6monLabEQgkll23MQMZaI1dVgaA0AcNSghF63C2vc9dkBAFCARQIA48ka7YBaJIJIQhJCCDRBABY9QhDWonhJdRwrRWbzkkwjsFglmGGAZoYKWk-o1wfhhTQqAUBxEJfQbSuk628UWlAVQ5kYDPBNfosh2BLVmKoTPKxsxbGaQ4c6pxbqSolS9ca3xEnWhxRCmFAJLlA0JYSqi%2BlyB2JMoGLZNL77yrYHyvfZRhBgAzTMitSyARkC41qa47aBU-p%2BFq2mlx7rtrbUBkJVrtT6DuoKttQgA9y2MAmmViruthssBGz%2Bcb5XsCzXdYVb2%2BtzLNNaZWzpHTkCgYAkXXFv5DvF2gDAWgQA&query=PTAEEUFcFMCcE9TwPaVqaAbaBbaA7AFwGdQALOaAGlAAdZoAzOAQwCNNEB3AS0LIBQIUAANiAYwYEAdAHNohAELxAZAQAKFQEoR00AElGSVKHEt8AckKhIxaELASp%2Ba7dHjkRFj3xxpARxgEAGUsaHFCZFgNbWkBexMPQi8fWH9A%2BBDscMi1c29aSEJzTQFHaBl5JXgAJWRsXLx8SD5cWBYAEx5kcxoAbwF8FjwALlBzAFF8WUweYjJzAQBfTSA

**Comment by delca85** [comment]
The right query here should be an `getByAltText` one, right?
I could give it a shot if you are ok with it.

**Comment by delca85** [comment]
According to [official documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Technical_summary) the suggestion is right, because the img has a non empty alt attribute. So it's the error in the panel the problem. Do you agree?

**Comment by smeijer** [comment]
Yes I agree. The suggestion is right. The error is indeed the problem.

**Comment by delca85** [comment]
Ok, if you agree I could try to fix it.

**Comment by smeijer** [comment]
Sure, go ahead :+1:

**Comment by delca85** [comment]
I think I found the bug issue: the suggestion is wrong! This is because of `aria-hidden` is set to `true`. This attribute makes the role not accessible, like explained [here](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-hidden_attribute#Description). So maybe it it is the suggestion that should take care of this attribute value and proposed another query (maybe the `getByAltText` one in this case).

**Comment by smeijer** [comment]
Thanks for the research. That makes a lot of sense.

Do you have an idea/suggestion for how we can fix this?

**Comment by delca85** [comment]
My idea would be adding a check [before](https://github.com/smeijer/testing-playground/blob/2b2c6fa37879b7a3887f5182cebcaf325335cd82/src/lib/queryAdvise.js#L20) trying to retrieve the element role. The element role will be retrieved only if the `aria-hidden` attribute is not set to true, in case of `aria-hidden` attribute value would be true, the role would be `undefined`.

This is my idea but any suggestion would be really appreciated.

**Comment by smeijer** [comment]
Sounds good to me. Can you create a PR?

**Comment by delca85** [comment]
I am going to create the PR with this bug fix but I have now noticed that there is another misleading behavior (or a behavior I am not sure to understand).
In `PreviewHint` the `accessibleRoles` are shown and these roles are retrieved using [`getRoles`](https://github.com/smeijer/testing-playground/blob/2b2c6fa37879b7a3887f5182cebcaf325335cd82/src/parser.js#L206) by [@testing-library/dom](https://github.com/testing-library/dom-testing-library). This method returns all the roles without any check about their accessibility.
In the same section of helpers method there is [isInaccessible](https://testing-library.com/docs/dom-testing-library/api-helpers#isinaccessible) that computes the accessibility by role of an element according to ARIA [criteria](https://www.w3.org/TR/wai-aria-1.2/#tree_exclusion).

**Comment by smeijer** [comment]
I think we can fix that issue by iterating over the `getRoles` result, and checking the elements with `isInaccessible`? Filter out those elements that are inaccessible. And if non of the elements under a role are accessible, remove that role from the list?

**Comment by delca85** [comment]
I was wrong, `getRoles` already [discriminates](https://github.com/eps1lon/dom-testing-library/blob/2a366f8f52b137d6222d26f0106e69230b702e12/src/role-helpers.js#L121) inaccessible roles so we don't need to add any logic.

**Comment by smeijer** [comment]
fixed by #104
