### ISSUE TITLE
Add option to copy suggestion to clipboard

### ISSUE THREAD

**Issue by ljosberinn** [smeijer/testing-playground#92]
Mayble introduce a setting checkbox that when checked, enables copy-to-clipboard on the `suggested query` box?

![image](https://user-images.githubusercontent.com/29307652/83822684-08405c00-a6d2-11ea-9f27-3bee386867db.png)

**Comment by smeijer** [comment]
Sounds great! Thanks.

I think we can add a "copy to clipboard" icon, like react-devtools have. Would that work for you?

![image](https://user-images.githubusercontent.com/1196524/83846700-4e65e180-a70b-11ea-8f45-afd0c0248173.png)

**Comment by smeijer** [comment]
Quick mockup, that would look something like:

![image](https://user-images.githubusercontent.com/1196524/83847021-d5b35500-a70b-11ea-9654-31c01f256731.png)

<details><summary>used svg:</summary>
<p>

```html
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <path d="M0 0h24v24H0z" fill="none"></path>
  <path fill="currentColor" d="
  M3 13h2v-2H3v2zm0 4h2v-2H3v2zm2 4v-2H3a2 2 0 0 0 2 2zM3 9h2V7H3v2zm12 12h2v-2h-2v2zm4-18H9a2 2 0 0 0-2
  2v10a2 2 0 0 0 2 2h10c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm0 12H9V5h10v10zm-8 6h2v-2h-2v2zm-4 0h2v-2H7v2z
"></path>
</svg>
```

</p>
</details>

**Comment by ljosberinn** [comment]
Looks great, I'll give it a shot at implementing it this evening. :)
